---
- name: Installing system dependencies from pip
  become: true
  pip:
    executable: pip
    name:
      - docker
      - docker-compose
    state: latest

- name: Removing existing instalations
  become: true
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent
  when: bootstraping is defined

- name: Installing packages to access https repository
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Adding docker key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present

- name: Adding docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Installing docker
  become: true
  apt:
    name: docker-ce
    state: present
    force: yes
    update_cache: yes
  notify:
  - reload docker
  - restart docker

- name: Starting docker service
  service:
    name: docker
    state: started

- name: Adding existing users to group docker
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  become: true
  loop: "{{ docker_users }}"
